# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - www/

pages:
  script:
    - move www public
  artifacts:
    paths:
      - public
  only:
    - master
