# This file is a template, and might need editing before it works on your project.
image: node:latest

pages:
  script:
    - mv ./www ./public

  artifacts:
    paths:
      - public
  only:
    - master
