# This file is a template, and might need editing before it works on your project.
image: rust:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/.cache/sccache
    - cache/.cargo
    - cache/.rustup
    - cache/.npm
    - cache/.nvm

before_script:
  - export HOME=cache
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install node
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - cargo install cargo-generate

pages:
  script:
    - export HOME=cache
    - wasm-pack build
    - cd www && npm install
    - npm run build
    - mv ./dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
